FROM alpine:latest

# Update package index
RUN apk update

# Install essential tools
RUN apk add --no-cache build-base curl ca-certificates libtool  openssl libffi 

# Install PostgreSQL
RUN apk add --no-cache postgresql-dev postgresql-client

# Download and install pgAudit
RUN mkdir -p /tmp/pgaudit && cd /tmp/pgaudit && \
    curl -L https://github.com/pgaudit/pgaudit/archive/16.0.tar.gz | tar xz --strip 1 && \
    make -C /tmp/pgaudit/ install USE_PGXS=1


# CMD ["postgres"]