services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            BROWSERSHOT_REMOTE_URL: 'insight-chromium'
            PUPPETEER_CACHE_DIR: '/home/sail/.cache/puppeteer'
        volumes:
            - 'tmpfiles:/tmp'
            - '.:/var/www/html:cached'
        networks:
            - InsightNet
        depends_on:
            - insightdb
            - insight-selenium
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 5
        entrypoint: >
            sh -c "npm install puppeteer@22.13.1 &&
                   npx puppeteer browsers install chrome &&
                   /usr/bin/supervisord -n"
    insightdb:
        # image: postgres:16-alpine
        build:
            context: ./dockerfiles
            dockerfile: dockerfile.insightdb
        ports:
            - '${FORWARD_DB_PORT:-5433}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sail-pgsql:/var/lib/postgresql/data'
            - './vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - InsightNet
        command: ["-c", "shared_preload_libraries=pgaudit"]
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -q -d ${DB_DATABASE} -U ${DB_USERNAME}"]
            interval: 10s
            retries: 3
            timeout: 5s
    InsightMailUI:
        image: mailhog/mailhog
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - InsightNet
    insight-pgadmin:
        build:
            context: ./dockerfiles
            dockerfile: dockerfile.pgadmin
        ports:
            - "5050:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: '${PGADMIN_EMAIL}'
            PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_PASSWORD:-secret}'
        volumes:
            - 'pgadmin:/var/lib/pgadmin'
            - '.:/var/lib/pgadmin/pgadmin4.conf'
        depends_on:
            - insightdb
        networks:
            - InsightNet
    insight-selenium:
        image: 'selenium/standalone-chromium'
        extra_hosts:
        - 'host.docker.internal:host-gateway'
        volumes:
            - '/dev/shm:/dev/shm'
        networks:
            - InsightNet

networks:
    InsightNet:
        driver: bridge
        # ipam:
        #     driver: default
        #     config:
        #         - subnet: "172.22.0.1/24"
volumes:
    sail-pgsql:
        driver: local
    pgadmin:
        driver: local
    tmpfiles:
        driver: local
